{% set name = "estimagic" %}
{% set version = "0.3.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/estimagic-{{ version }}.tar.gz
  sha256: 960d970c79ef5ae657a1690ea5a80b948ec68ea233321a623f4dc998cfc7a06e

build:
  number: 0
  noarch: python
  entry_points:
    - estimagic=estimagic.cli:cli
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - bokeh >=1.3
    - click
    - cloudpickle
    - dill
    - fuzzywuzzy
    - joblib
    - numpy >=1.16
    - pandas >=1.0
    - python >=3.8
    - scipy
    - seaborn
    - sqlalchemy >=1.3
    - pybaum >=0.1.1
    - plotly

test:
  imports:
    - estimagic
  commands:
    - estimagic --help
  requires:
    - pip

about:
  home: https://github.com/OpenSourceEconomics/estimagic
  summary: Tools for the estimation of (structural) econometric models.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - janosg
