{% set name = "estimagic" %}
{% set version = "0.5.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/estimagic-{{ version }}.tar.gz
  sha256: 497da1496c28e595763185301930491cca0ddae5f37a00412d637257ca386352

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.10
    - hatchling
    - hatch-vcs
    - pip
    - toml
  run:
    - python >=3.10
    - cloudpickle
    - joblib
    - numpy <2.0
    - pandas
    - plotly
    - pybaum >=0.1.2
    - scipy >=1.2.1
    - sqlalchemy >=1.3
    - annotated-types
    - typing-extensions
    - jinja2

test:
  imports:
    - optimagic
  commands:
    - pip check
  requires:
    - pip
    
about:
  home: https://github.com/optimagic-dev/optimagic
  summary: Tools for difficult nonlinear optimization problems.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - janosg
