{% set name = "estimagic" %}
{% set version = "0.3.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/estimagic-{{ version }}.tar.gz
  sha256: 7a441bbc7be6270b74cf21f4d7dfe7a40fb7d96af83552ca2197cf5b24208bac

build:
  number: 0
  noarch: python
  entry_points:
    - estimagic=estimagic.cli:cli
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - bokeh >=1.3
    - click
    - cloudpickle
    - fuzzywuzzy
    - joblib
    - numpy >=1.16
    - pandas >=1.0
    - python >=3.8
    - scipy
    - sqlalchemy >=1.3
    - pybaum >=0.1.2
    - plotly

test:
  imports:
    - estimagic
  commands:
    - estimagic --help
  requires:
    - pip

about:
  home: https://github.com/OpenSourceEconomics/estimagic
  summary: Tools for the estimation of (structural) econometric models.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - janosg
