{% set name = "estimagic" %}
{% set version = "0.4.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/estimagic-{{ version }}.tar.gz
  sha256: 824d8851a4bea3d44739e8a8f8600051f1e3059da6b7c5ce3d9e80d52a7ef3b4

build:
  number: 0
  noarch: python
  entry_points:
    - estimagic=estimagic.cli:cli
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - bokeh >=1.3
    - click
    - cloudpickle
    - fuzzywuzzy
    - joblib
    - numpy >=1.17
    - pandas >=1.0
    - python >=3.8
    - scipy
    - sqlalchemy >=1.3
    - pybaum >=0.1.2
    - plotly
    - numba

test:
  imports:
    - estimagic
  commands:
    - estimagic --help
  requires:
    - pip

about:
  home: https://github.com/OpenSourceEconomics/estimagic
  summary: Tools for the estimation of (structural) econometric models.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - janosg
