{% set name = "estimagic" %}
{% set version = "0.2.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/estimagic-{{ version }}.tar.gz
  sha256: b337879d718d3229aafd407821ce2744d58a82f8c617cb4349c2aceb003e8827

build:
  number: 0
  noarch: python
  entry_points:
    - estimagic=estimagic.cli:cli
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - bokeh >=1.3
    - click
    - cloudpickle
    - dill
    - fuzzywuzzy
    - joblib
    - numpy >=1.16
    - pandas >=1.0
    - python >=3.8
    - scipy
    - seaborn
    - sqlalchemy >=1.3
    - chaospy
    - pybaum>=0.1.1

test:
  imports:
    - estimagic
  commands:
    - estimagic --help
  requires:
    - pip

about:
  home: https://github.com/OpenSourceEconomics/estimagic
  summary: Tools for the estimation of (structural) econometric models.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - janosg
