{% set name = "estimagic" %}
{% set version = "0.4.5" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/estimagic-{{ version }}.tar.gz
  sha256: 40ef9011816521d466c91e1a20c64d0929fa4141aad1ee20bbc5370d4423cd98

build:
  number: 0
  noarch: python
  entry_points:
    - estimagic=estimagic.cli:cli
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools-scm
    - toml
  run:
    - bokeh <=2.4.3
    - click
    - cloudpickle
    - joblib
    - numpy >=1.17
    - pandas >=1.0
    - python >=3.8
    - scipy >=1.7
    - sqlalchemy >=1.3
    - pybaum >=0.1.2
    - plotly
    - numba

test:
  imports:
    - estimagic
  commands:
    - estimagic --help
  requires:
    - pip

about:
  home: https://github.com/OpenSourceEconomics/estimagic
  summary: Tools for difficult nonlinear optimization problems.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - janosg
